sudo: false # use containers
language: java
cache:
  directories:
    - "$HOME/.m2" # Maven dependencies
jdk:
  - oraclejdk8
script:
  - mvn -Dispyb.url=jdbc:mariadb://localhost:3306 -Dispyb.user=root -Dispyb.host=localhost package
  - sonar-scanner
addons:
  mariadb: '10.2'
  sonarqube:
    token:
      secure: ei93Y9Nw5Jx8cfY92D5Xm/hBENmgnUOxAaIIEO0zkeDgTgSE884C/nCCD9fqxmeRdUFAAbGt8tXbDv0xEI1ucGLYicBE6Z5E7WT3ujsh7JJOnJ/FO8rT2hobMH27kA7a/vdXl4cPIPKXRf13CDgzRarPqqobW8b/VHNt1haRCuzJaFXzXgE0NNv+7kRUhZEr+jlR73RKzhTPnUiVYWXETD4uBBRW0wFBhu9SSFesI7Pef01QLEEunRmEy+XvD/e4UCQeCtTN5A+nm+il+emKxigH/iib+Vu/LQMuUJ9v31gzKwt2B2gjY9s/uLNiqiHwNWUtCqKzwLNIfmBahn8pdflSXLHq9eJs5anfGPYXpxouSTiB08zcsCJ07BAXnxHwkZk5ARLMIEke00MBREvH/cDKu7hygIbCGCpd8VFtID5CFzSHC3Nf+W8NUlZlDOTTyBiUKK54OMfsGzczKOP1tZECJfKuUkNNJn4lBRPEaGFqQhWXvu3MG4j1fp3E+LM0eQk9KfsBSUnHoPhIKC55eQ5B6EaU8VtMnzLsrryxqIDXYoOuCEjlEt7GoaXUWArQ2kpgT7ZUZhFLkGOagjW8fS+PS3IglpP6mf+yPKiwbHJazbQdwl6ZJ+W4QHMJ8eySjObSXAH3S2r3f/Ke+MZlsj3gRxCQMZPowUMNX3NPwms=
deploy:
  provider: releases
  api_key:
    secure: xCYbMcMHSBcaqoSC7+rnMCD0eoQOW05VDAz8ctW0H5MujR+buEHlrIRduBDRiRokJUVaPyspur1y+4V4b9H2+YNutQ/5svxLxtgSq0XD3r58ZE++67jcUMOAK39Xgm8hddzRy+VKhMOZ4mX9IxYz/dMwY4+WaVFZ0i57ktvjSLgLrLPTvKSNYhjT7H1G0OBdPzi8K6KVMabn8/p1wTWtWzvTc6rsevy6M8pBuv/u07fHvRhdSDDIw56ScEV5YPQ6XVFLifT9yYwJYmoXPqCnzM1fvA4uOWtmH7ApDZm4CAurFHZFLRwvCrtXfXj+zAWIWMasfNgtuDZFPQoeEtJZKh2DyqKNwMF+xjclji0jGCC7QFA/M8ozAsszUixJvgLvxu871/HVjZnKXbgCrTW6tCs/YFT3NcZgRT9YPpsNuh7XutVjI9G77i9+DPzEQ63K1dfNXUkqtSIpg2Rhdpib7FPgUrhpc2AJPhQpf3b4Ev/Tsc9ItWUcw6jwqbmXYMyeW8cyzA3oVUEW+mZtUkMrWUqIN/tiUTOqvV4QkdVRusqbd1eNp6yrYNOiNlGQCGMYTlxWV8JW2vwzDCj1B4Eef3LDyN0eYhAxTF0jV23wcbj/fWHkpcCjjOPxsLPDiHwYs5vIPsoa0f5/L9rtJEHU282pFcQQTiZXxICJwalVFYM=
  file_glob: true
  file:
    - "target/ispyb-api-*.jar"
  skip_cleanup: true
  on:
    tags: true
