dist: trusty
language: java
cache:
  directories:
    - "$HOME/.m2" # Maven dependencies
jdk:
  - oraclejdk8
script:
    #- mysql -e "SET GLOBAL time_zone='+1:00'"
  - mvn -Dispyb.url='jdbc:mariadb://localhost:3306' -Dispyb.user=root -Dispyb.host=localhost package
addons:
  mariadb: '10.3'
deploy:
  provider: releases
  api_key:
    secure: xCYbMcMHSBcaqoSC7+rnMCD0eoQOW05VDAz8ctW0H5MujR+buEHlrIRduBDRiRokJUVaPyspur1y+4V4b9H2+YNutQ/5svxLxtgSq0XD3r58ZE++67jcUMOAK39Xgm8hddzRy+VKhMOZ4mX9IxYz/dMwY4+WaVFZ0i57ktvjSLgLrLPTvKSNYhjT7H1G0OBdPzi8K6KVMabn8/p1wTWtWzvTc6rsevy6M8pBuv/u07fHvRhdSDDIw56ScEV5YPQ6XVFLifT9yYwJYmoXPqCnzM1fvA4uOWtmH7ApDZm4CAurFHZFLRwvCrtXfXj+zAWIWMasfNgtuDZFPQoeEtJZKh2DyqKNwMF+xjclji0jGCC7QFA/M8ozAsszUixJvgLvxu871/HVjZnKXbgCrTW6tCs/YFT3NcZgRT9YPpsNuh7XutVjI9G77i9+DPzEQ63K1dfNXUkqtSIpg2Rhdpib7FPgUrhpc2AJPhQpf3b4Ev/Tsc9ItWUcw6jwqbmXYMyeW8cyzA3oVUEW+mZtUkMrWUqIN/tiUTOqvV4QkdVRusqbd1eNp6yrYNOiNlGQCGMYTlxWV8JW2vwzDCj1B4Eef3LDyN0eYhAxTF0jV23wcbj/fWHkpcCjjOPxsLPDiHwYs5vIPsoa0f5/L9rtJEHU282pFcQQTiZXxICJwalVFYM=
  file_glob: true
  file:
    - "target/ispyb-api-*.jar"
  skip_cleanup: true
  on:
    tags: true
